language: minimal

sudo: required
dist: trusty

env:
  - DOCKER_CLI_EXPERIMENTAL=enabled

before_script:
  - sudo service docker restart

script: make all lint scan

branches:
    only:
        - master
        - /\/ci$/

notifications:
  email: false
